### ISSUE TITLE
Does it matter where I install this plugin ? Any preference ?

### ISSUE THREAD

**Issue by kiranshashiny** [bevywise-networks/mqttroute-elasticsearch-connector#2]
```
$ pwd
/Users/shashikiran/Downloads/bevywise/Bevywise/MQTTRoute


$ ls
Broker.pid					conf						mqttroute-elasticsearch-connector-master
Certificate					data						mqttroute-elasticsearch-connector-master.zip
README						lib						web
bin						license
```

**Comment by kiranshashiny** [comment]
Suggest a Slack Channel in general for Bevywise. So others can benefit too. Just a suggestion.
One can post snapshots in it and will help others if they want to scroll back and look at suggestions from your support.

**Comment by bevywise** [comment]
Thank you very much for your suggestion. Sorry for the delayed response. 

We will make sure we set it up at the earliest.
